name: Create Azure Storage Account

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  repository_dispatch: # Allows triggering via external tools like ServiceNow
    types:
      - create-storage-account

jobs:
  terraform:
    name: Create Storage Account
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.3 # Specify your Terraform version here

    # Step 3: Authenticate to Azure using a Service Principal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    # Step 6: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -var-file="terraform.tfvars" -auto-approve
